// Visual JSX source: axel-workforce-os/src/components/deal-card/MarketCorrespondenceView.tsx.
// API calls are intentionally replaced with local state for sandbox-only preview.
import { useState } from "react";
import { AlertCircle, CheckCircle2, Clock, EyeOff, Mail, RefreshCw, Send } from "lucide-react";
import type { Message } from "./types";
import { c } from "./types";
function MessageItem({ message }: { message: Message }) {
  const inbound = message.direction === "INBOUND"; const date = message.receivedAt || message.sentAt;
  const time = date ? new Date(date).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "";
  return <div style={{ background: inbound ? c.cardBg : c.bg, border: `1px solid ${c.borderColor}`, borderRadius: 10, padding: 12, display: "flex", flexDirection: "column", gap: 8, marginLeft: inbound ? 0 : 24, marginRight: inbound ? 24 : 0, borderLeft: inbound ? "3px solid var(--accent-primary)" : `1px solid ${c.borderColor}` }}>
    <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><div><div style={{ fontSize: 13, fontWeight: 600, color: c.textPrimary }}>{inbound ? (message.from.name || message.from.email) : "Axel Staff"}</div>{message.subject && <div style={{ fontSize: 12, fontWeight: 500, color: c.textSecondary }}>Subject: {message.subject}</div>}</div><div style={{ display: "flex", alignItems: "center", gap: 8 }}><span style={{ fontSize: 11, color: c.textMuted }}>{time}</span>{!inbound && <CheckCircle2 size={14} color="#22a06b" />}</div></div>
    <div style={{ fontSize: 11, color: c.textMuted, display: "flex", flexDirection: "column" }}>{inbound && <span>From: {message.from.email}</span>}<span>To: {message.to.join(", ")}</span></div>
    <div style={{ fontSize: 13, color: c.textPrimary, lineHeight: 1.5, whiteSpace: "pre-wrap" }}>{message.enrichment === "PENDING" ? <span style={{ color: c.textMuted, fontStyle: "italic" }}><Clock size={14} /> Retrieving message body...</span> : message.bodyText}</div>
  </div>;
}
export function MarketCorrespondenceView({ marketName, contact, messages, onAdd }: { marketName: string; contact: string; messages: Message[]; onAdd: (message: Message) => void }) {
  const [subject, setSubject] = useState(""); const [text, setText] = useState(""); const [confirm, setConfirm] = useState(false);
  const send = () => { onAdd({ id: String(Date.now()), direction: "OUTBOUND", from: { email: "csa@axel.example" }, to: [contact], subject: subject || `Update regarding ${marketName}`, bodyText: text, sentAt: new Date().toISOString(), deliveryState: "sent" }); setSubject(""); setText(""); setConfirm(false); };
  return <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
    <div style={{ background: c.bg, border: `1px dashed ${c.borderColor}`, borderRadius: 8, padding: 12, display: "flex", gap: 12 }}><EyeOff size={16} color="var(--accent-primary)" style={{ marginTop: 2, flexShrink: 0 }} /><div><div style={{ fontSize: 13, fontWeight: 600, color: c.textPrimary }}>Private Market Correspondence</div><div style={{ fontSize: 12, color: c.textSecondary, marginTop: 4 }}>This conversation is visible only to Axel Admins and CSAs. Messages are sent directly to the verified market contact.</div><div style={{ fontSize: 11, color: c.textMuted, marginTop: 7 }}><strong>Contact:</strong> {contact}</div></div></div>
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>{messages.length ? messages.map(m => <MessageItem key={m.id} message={m} />) : <div style={{ fontSize: 12, color: c.textMuted, padding: "20px 0", textAlign: "center" }}>No messages yet.</div>}</div>
    <div style={{ background: c.cardBg, border: `1px solid ${c.borderColor}`, borderRadius: 10, padding: 14, display: "flex", flexDirection: "column", gap: 10 }}><div style={{ fontSize: 12, fontWeight: 600, color: c.textPrimary, display: "flex", gap: 6, alignItems: "center" }}><Mail size={14} /> New Message to {marketName}</div><input value={subject} onChange={e => setSubject(e.target.value)} placeholder={`Subject (defaults to: Update regarding ${marketName})`} style={{ width: "100%", background: c.bg, border: `1px solid ${c.borderColor}`, borderRadius: 6, padding: "8px 12px", fontSize: 13, color: c.textPrimary }} /><textarea value={text} onChange={e => setText(e.target.value)} placeholder={`Type your message to ${contact}...`} style={{ width: "100%", minHeight: 82, background: c.bg, border: `1px solid ${c.borderColor}`, borderRadius: 6, padding: "10px 12px", fontSize: 13, color: c.textPrimary, resize: "vertical" }} />
      <div style={{ display: "flex", justifyContent: "flex-end" }}>{confirm ? <div style={{ display: "flex", alignItems: "center", gap: 10, background: "rgba(239,68,68,.1)", border: "1px solid rgba(239,68,68,.3)", padding: "8px 12px", borderRadius: 8 }}><span style={{ fontSize: 12, color: "#ef4444", fontWeight: 600 }}>Confirm send to {contact}?</span><button onClick={() => setConfirm(false)} style={{ fontSize: 11, background: "none", border: `1px solid ${c.borderColor}`, color: c.textSecondary, borderRadius: 4, padding: "4px 8px" }}>Cancel</button><button onClick={send} style={{ fontSize: 11, background: "#ef4444", border: "none", color: "#fff", borderRadius: 4, padding: "4px 8px", fontWeight: 600 }}>Confirm Send</button></div> : <button onClick={() => setConfirm(true)} disabled={!text.trim()} style={{ display: "flex", alignItems: "center", gap: 6, background: "var(--accent-primary)", color: "#fff", border: "none", borderRadius: 6, padding: "8px 16px", fontSize: 13, fontWeight: 600, opacity: text.trim() ? 1 : .6 }}><Send size={14} /> Send to Market</button>}</div>
    </div>
  </div>;
}