/**
 * Development-only browser fixture for controlled correspondence review.
 * Setup writes opaque session cookies only to .local/browser-correspondence-
 * fixture.json; never copy that private file into source control or chat.
 *
 *   pnpm exec tsx src/scripts/browser-correspondence-fixture.ts setup
 *   pnpm exec tsx src/scripts/browser-correspondence-fixture.ts cleanup
 */
import { randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { eq, inArray } from "drizzle-orm";
import {
  accountsTable,
  activityLogTable,
  correspondenceThreadsTable,
  db,
  dealInboundEmailsTable,
  dealMarketsTable,
  dealOutboundEmailsTable,
  dealsTable,
  marketUnderwritersTable,
  marketsTable,
  orgMembersTable,
  organizationsTable,
  sessionsTable,
  trustedAxelOrganizationsTable,
  usersTable,
} from "@workspace/db";
import { createSession } from "../lib/auth.js";

const AUTHORIZED_AXEL_ORG_ID = "00000000-0000-0000-0000-000000000001";
const workspaceRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const fixturePath = resolve(workspaceRoot, ".local/browser-correspondence-fixture.json");

type Fixture = {
  fixtureTag: string;
  accountId: string;
  organizationIds: string[];
  dealIds: string[];
  marketIds: string[];
  underwriterIds: string[];
  threadIds: string[];
  heldMessageIds: string[];
  userIds: string[];
  names: {
    ownDeals: string[];
    ownMarkets: string[];
    unmatchedSubject: string;
    foreignSubject: string;
  };
  // Kept private so the browser tester can set the development cookie without
  // emitting secrets to stdout or storing a password.
  adminCookie: string;
  csaCookie: string;
  externalAgentCookie: string;
};

async function cleanup(fixture: Fixture) {
  // Every predicate uses IDs generated by this fixture. Inbound rows are
  // removed first because the unmatched row intentionally has no deal ID.
  if (fixture.heldMessageIds.length) {
    await db.delete(dealInboundEmailsTable).where(inArray(dealInboundEmailsTable.id, fixture.heldMessageIds));
  }
  if (fixture.dealIds.length) {
    await db.delete(activityLogTable).where(inArray(activityLogTable.dealId, fixture.dealIds));
    await db.delete(dealOutboundEmailsTable).where(inArray(dealOutboundEmailsTable.dealId, fixture.dealIds));
  }
  if (fixture.threadIds.length) {
    await db.delete(correspondenceThreadsTable).where(inArray(correspondenceThreadsTable.id, fixture.threadIds));
  }
  if (fixture.dealIds.length) {
    await db.delete(dealMarketsTable).where(inArray(dealMarketsTable.dealId, fixture.dealIds));
    await db.delete(dealsTable).where(inArray(dealsTable.id, fixture.dealIds));
  }
  if (fixture.underwriterIds.length) {
    await db.delete(marketUnderwritersTable).where(inArray(marketUnderwritersTable.id, fixture.underwriterIds));
  }
  if (fixture.marketIds.length) {
    await db.delete(marketsTable).where(inArray(marketsTable.id, fixture.marketIds));
  }
  if (fixture.userIds.length) {
    await db.delete(sessionsTable).where(inArray(sessionsTable.userId, fixture.userIds));
    await db.delete(orgMembersTable).where(inArray(orgMembersTable.userId, fixture.userIds));
    await db.delete(usersTable).where(inArray(usersTable.id, fixture.userIds));
  }
  await db.delete(accountsTable).where(eq(accountsTable.id, fixture.accountId));
  if (fixture.organizationIds.length) {
    await db.delete(organizationsTable).where(inArray(organizationsTable.id, fixture.organizationIds));
  }
}

async function main() {
  if (process.env.NODE_ENV === "production") {
    throw new Error("This fixture script is Development-only and refuses production.");
  }
  const action = process.argv[2];
  if (action === "cleanup") {
    await cleanup(JSON.parse(await readFile(fixturePath, "utf8")) as Fixture);
    await rm(fixturePath, { force: true });
    process.stdout.write("Private browser fixture cleaned up.\n");
    return;
  }
  if (action !== "setup") throw new Error("Usage: browser-correspondence-fixture.ts setup|cleanup");

  // Idempotent setup replaces only a previous fixture recorded in the private
  // file. It never alters an existing organization, real deal, or trust row.
  try {
    await cleanup(JSON.parse(await readFile(fixturePath, "utf8")) as Fixture);
  } catch {
    // No prior private fixture is normal.
  }
  const [orgRows, trustedRows] = await Promise.all([
    db.select({ id: organizationsTable.id, status: organizationsTable.status }).from(organizationsTable)
      .where(eq(organizationsTable.id, AUTHORIZED_AXEL_ORG_ID)).limit(1),
    db.select({ orgId: trustedAxelOrganizationsTable.orgId }).from(trustedAxelOrganizationsTable)
      .where(eq(trustedAxelOrganizationsTable.orgId, AUTHORIZED_AXEL_ORG_ID)).limit(1),
  ]);
  const org = orgRows[0];
  const trusted = trustedRows[0];
  if (!org || org.status !== "ACTIVE" || !trusted) {
    throw new Error("The authorized active Axel Development organization/trust anchor is unavailable.");
  }

  const fixtureTag = `browser-correspondence-${randomUUID().replaceAll("-", "").slice(0, 12)}`;
  const [account] = await db.insert(accountsTable).values({
    businessName: `Fictional Browser Correspondence ${fixtureTag}`,
  }).returning({ id: accountsTable.id });
  const [externalOrg] = await db.insert(organizationsTable).values({
    name: `Fictional External Browser Org ${fixtureTag}`,
    type: "Agency",
    status: "ACTIVE",
  }).returning({ id: organizationsTable.id });
  const ownDealNames = [1, 2].map((index) => `Fictional Held Review Deal ${index} ${fixtureTag}`);
  const [firstDeal, secondDeal, foreignDeal] = await db.insert(dealsTable).values([
    ...ownDealNames.map((businessName, index) => ({
      referenceCode: `T-BR-${fixtureTag.slice(-6).toUpperCase()}-${index + 1}`,
      accountId: account.id,
      businessName,
      orgId: AUTHORIZED_AXEL_ORG_ID,
      stage: "UW_REVIEW",
      submissionStatus: "submitted",
    })),
    {
      referenceCode: `T-BR-${fixtureTag.slice(-6).toUpperCase()}-X`,
      accountId: account.id,
      businessName: `Fictional Foreign Held Deal ${fixtureTag}`,
      orgId: externalOrg.id,
      stage: "UW_REVIEW",
      submissionStatus: "submitted",
    },
  ]).returning({ id: dealsTable.id });
  const ownDeals = [firstDeal, secondDeal];

  const [admin, csa, externalAgent] = await db.insert(usersTable).values([
    { email: `${fixtureTag}-admin@example.test`, firstName: "Fictional", lastName: "Admin", status: "active" },
    { email: `${fixtureTag}-csa@example.test`, firstName: "Fictional", lastName: "CSA", status: "active" },
    { email: `${fixtureTag}-agent@example.test`, firstName: "Fictional", lastName: "External Agent", status: "active" },
  ]).returning({ id: usersTable.id });
  await db.insert(orgMembersTable).values([
    { userId: admin.id, orgId: AUTHORIZED_AXEL_ORG_ID, role: "ADMIN", isPrimaryOrg: true },
    { userId: csa.id, orgId: AUTHORIZED_AXEL_ORG_ID, role: "CSA", isPrimaryOrg: true },
    { userId: externalAgent.id, orgId: externalOrg.id, role: "AGENT", isPrimaryOrg: true },
  ]);
  const [adminSession, csaSession, externalAgentSession] = await Promise.all([
    createSession(admin.id),
    createSession(csa.id),
    createSession(externalAgent.id),
  ]);

  const marketNames = [1, 2].map((rank) => `Fictional Held Market ${rank} ${fixtureTag}`);
  const markets = await db.insert(marketsTable).values(marketNames.map((name) => ({
    name,
    marketType: "WC_CARRIER",
    productLane: "WC",
    isActive: true,
    isAppointed: true,
  }))).returning({ id: marketsTable.id });
  const underwriters = await db.insert(marketUnderwritersTable).values(markets.map((market, index) => ({
    marketId: market.id,
    name: `Fictional Contact ${index + 1}`,
    email: `${fixtureTag}-market-${index + 1}@example.test`,
    isActive: true,
  }))).returning({ id: marketUnderwritersTable.id, email: marketUnderwritersTable.email });
  const dealMarkets = await db.insert(dealMarketsTable).values(markets.map((market, index) => ({
    dealId: ownDeals[index].id,
    marketId: market.id,
    marketType: "WC_CARRIER",
    assignedUnderwriterId: underwriters[index].id,
    submissionEmailSnapshot: underwriters[index].email,
    engagementSource: "MANUAL_OVERFLOW",
    isActive: true,
    marketStatus: "ACTIVE",
    appetiteOutcome: "MATCHED",
    rankingState: "PROVISIONAL",
    sendStatus: "PENDING",
    rank: 1,
    isPrimary: true,
  }))).returning({ id: dealMarketsTable.id });
  const threads = await db.insert(correspondenceThreadsTable).values(dealMarkets.map((market, index) => ({
    dealId: ownDeals[index].id,
    dealMarketId: market.id,
    channel: "MARKET",
    listenerEmail: `${fixtureTag}-listener-${index + 1}@example.test`,
    subjectToken: `T${fixtureTag.slice(-10)}${index + 1}`,
  }))).returning({ id: correspondenceThreadsTable.id, listenerEmail: correspondenceThreadsTable.listenerEmail });

  const unmatchedSubject = `Fictional unmatched held mail ${fixtureTag}`;
  const foreignSubject = `Fictional foreign held mail ${fixtureTag}`;
  const held = await db.insert(dealInboundEmailsTable).values([
    ...ownDeals.map((deal, index) => ({
      dealId: deal.id,
      dealMarketId: dealMarkets[index].id,
      correspondenceThreadId: threads[index].id,
      messageId: `<${fixtureTag}-held-${index + 1}@example.test>`,
      fromEmail: underwriters[index].email,
      fromName: `Fictional Contact ${index + 1}`,
      toEmails: [threads[index].listenerEmail],
      ccEmails: [],
      subject: `Fictional candidate held reply ${index + 1}`,
      bodyText: `Fictional held text for deal and market ${index + 1}.`,
      bodyHtml: null,
      channel: "HELD",
      heldReason: "SENDER_NOT_APPROVED_FOR_THREAD",
      senderAuthEvidence: "informational fixture evidence only",
      bodyEnrichmentStatus: "COMPLETE",
      receivedAt: new Date(Date.now() - index * 1000),
      processedAt: new Date(),
    })),
    {
      dealId: null,
      messageId: `<${fixtureTag}-unmatched@example.test>`,
      fromEmail: `${fixtureTag}-unknown@example.test`,
      fromName: "Fictional Unknown Sender",
      toEmails: [`${fixtureTag}-unknown-listener@example.test`],
      ccEmails: [],
      subject: unmatchedSubject,
      bodyText: "Fictional unmatched held text.",
      bodyHtml: null,
      channel: "HELD",
      heldReason: "UNKNOWN_RECIPIENT",
      senderAuthEvidence: "informational fixture evidence only",
      bodyEnrichmentStatus: "COMPLETE",
      receivedAt: new Date(Date.now() - 2000),
      processedAt: new Date(),
    },
    {
      dealId: foreignDeal.id,
      messageId: `<${fixtureTag}-foreign@example.test>`,
      fromEmail: `${fixtureTag}-foreign@example.test`,
      fromName: "Fictional Foreign Sender",
      toEmails: [`${fixtureTag}-foreign-listener@example.test`],
      ccEmails: [],
      subject: foreignSubject,
      bodyText: "Fictional other-organization held text.",
      bodyHtml: null,
      channel: "HELD",
      heldReason: "UNKNOWN_RECIPIENT",
      senderAuthEvidence: "informational fixture evidence only",
      bodyEnrichmentStatus: "COMPLETE",
      receivedAt: new Date(Date.now() - 3000),
      processedAt: new Date(),
    },
  ]).returning({ id: dealInboundEmailsTable.id });

  const fixture: Fixture = {
    fixtureTag,
    accountId: account.id,
    organizationIds: [externalOrg.id],
    dealIds: [...ownDeals.map((deal) => deal.id), foreignDeal.id],
    marketIds: markets.map((market) => market.id),
    underwriterIds: underwriters.map((underwriter) => underwriter.id),
    threadIds: threads.map((thread) => thread.id),
    heldMessageIds: held.map((message) => message.id),
    userIds: [admin.id, csa.id, externalAgent.id],
    names: {
      ownDeals: ownDealNames,
      ownMarkets: marketNames,
      unmatchedSubject,
      foreignSubject,
    },
    adminCookie: `axel_session=${adminSession.token}`,
    csaCookie: `axel_session=${csaSession.token}`,
    externalAgentCookie: `axel_session=${externalAgentSession.token}`,
  };
  await mkdir(dirname(fixturePath), { recursive: true, mode: 0o700 });
  await writeFile(fixturePath, `${JSON.stringify(fixture, null, 2)}\n`, { mode: 0o600 });
  await chmod(fixturePath, 0o600);
  process.stdout.write("Private browser fixture prepared.\n");
}

await main();