// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/accounts-list/GroupedRows.tsx": () => import("../components/mockups/accounts-list/GroupedRows.tsx"),
  "./components/mockups/accounts-list/ListRows.tsx": () => import("../components/mockups/accounts-list/ListRows.tsx"),
  "./components/mockups/accounts-list/TableRows.tsx": () => import("../components/mockups/accounts-list/TableRows.tsx"),
  "./components/mockups/aesthetic-refresh/DashboardPreview.tsx": () => import("../components/mockups/aesthetic-refresh/DashboardPreview.tsx"),
  "./components/mockups/aesthetic-refresh/MarketplacePreview.tsx": () => import("../components/mockups/aesthetic-refresh/MarketplacePreview.tsx"),
  "./components/mockups/aesthetic-refresh/SidebarPreview.tsx": () => import("../components/mockups/aesthetic-refresh/SidebarPreview.tsx"),
  "./components/mockups/deal-docs/Checklist.tsx": () => import("../components/mockups/deal-docs/Checklist.tsx"),
  "./components/mockups/deal-docs/FileTable.tsx": () => import("../components/mockups/deal-docs/FileTable.tsx"),
  "./components/mockups/deal-docs/GroupedSections.tsx": () => import("../components/mockups/deal-docs/GroupedSections.tsx"),
  "./components/mockups/deal-feed/CleanCards.tsx": () => import("../components/mockups/deal-feed/CleanCards.tsx"),
  "./components/mockups/deal-feed/IconTimeline.tsx": () => import("../components/mockups/deal-feed/IconTimeline.tsx"),
  "./components/mockups/deal-feed/QuietSystem.tsx": () => import("../components/mockups/deal-feed/QuietSystem.tsx"),
  "./components/mockups/deal-feed/SimpleLines.tsx": () => import("../components/mockups/deal-feed/SimpleLines.tsx"),
  "./components/mockups/deal-feed/TwoLane.tsx": () => import("../components/mockups/deal-feed/TwoLane.tsx"),
  "./components/mockups/deal-feed/TwoLaneGrouped.tsx": () => import("../components/mockups/deal-feed/TwoLaneGrouped.tsx"),
  "./components/mockups/deal-feed/TwoLaneIcons.tsx": () => import("../components/mockups/deal-feed/TwoLaneIcons.tsx"),
  "./components/mockups/deal-feed/TwoLaneSoft.tsx": () => import("../components/mockups/deal-feed/TwoLaneSoft.tsx"),
  "./components/mockups/deal-feed/TypedRows.tsx": () => import("../components/mockups/deal-feed/TypedRows.tsx"),
  "./components/mockups/implementations-view/CommandCenter.tsx": () => import("../components/mockups/implementations-view/CommandCenter.tsx"),
  "./components/mockups/implementations-view/GoLiveTimeline.tsx": () => import("../components/mockups/implementations-view/GoLiveTimeline.tsx"),
  "./components/mockups/implementations-view/PhaseBoard.tsx": () => import("../components/mockups/implementations-view/PhaseBoard.tsx")
};
