/**
 * Phase 4C — supporting tabs (Documents / Tasks / Quote / Policy). These wrap
 * the pre-existing functional panels and endpoints so the hub preserves the
 * deal card's prior capabilities while the Overview + Submission tabs deliver
 * the new collaboration experience.
 */
import { useCallback, useEffect, useState } from "react";
import { FileText, File, Eye, Download, CheckSquare, Plus, Calculator, Shield } from "lucide-react";
import { api } from "@/lib/api";
import { useThemeColors } from "@/lib/use-theme-colors";
import { PinkButton, GhostButton } from "@/components/ui/axel-index";
import IndicationBreakdownPanel from "@/components/IndicationBreakdownPanel";
import IndicationDetailView, { type IndicationMetric, type WorkforceProfileShape } from "./IndicationDetailView";
import ProposalPanel from "@/components/ProposalPanel";
import BindStatusPanel from "@/components/submission/BindStatusPanel";
import UserMiniProfile from "@/components/user-profile/UserMiniProfile";
import PolicyDocumentsPanel from "./PolicyDocumentsPanel";
import PdfPreviewModal from "./PdfPreviewModal";

/* ---------------------------------------------------------------- Documents */
type DealDocument = {
  id: string;
  name: string;
  documentType: string;
  status: string;
  generatedAt?: string;
  metadata?: { downloadPath?: string } | null;
};
type CannabisPdf = { documentType: string; label: string; path: string };

/** One uniform document row: icon, name, muted meta, preview/download actions. */
function DocRow({
  icon,
  name,
  meta,
  url,
  onPreview,
  last,
  testId,
}: {
  icon: React.ReactNode;
  name: string;
  meta?: string;
  url?: string;
  onPreview?: () => void;
  last?: boolean;
  testId: string;
}) {
  const c = useThemeColors();
  return (
    <div
      data-testid={testId}
      style={{
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "11px 14px",
        borderBottom: last ? "none" : `1px solid ${c.borderColor}`,
      }}
    >
      {icon}
      <span style={{ fontSize: 13, fontWeight: 500, color: c.textPrimary, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
        {name}
      </span>
      {meta && (
        <span style={{ fontSize: 11.5, color: c.textMuted, whiteSpace: "nowrap" }}>• {meta}</span>
      )}
      <span style={{ flex: 1 }} />
      {url && onPreview && (
        <button
          type="button"
          onClick={onPreview}
          aria-label={`Preview ${name}`}
          data-testid={`${testId}-preview`}
          style={{ display: "inline-flex", padding: 5, background: "transparent", border: "none", color: c.textMuted, cursor: "pointer" }}
        >
          <Eye style={{ width: 15, height: 15 }} />
        </button>
      )}
      {url && (
        <a
          href={url}
          download
          aria-label={`Download ${name}`}
          data-testid={`${testId}-download`}
          style={{ display: "inline-flex", padding: 5, color: "var(--accent-primary)" }}
        >
          <Download style={{ width: 15, height: 15 }} />
        </a>
      )}
    </div>
  );
}

const SECTION_LABEL: React.CSSProperties = {
  fontSize: 11,
  fontWeight: 600,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  margin: "0 0 10px",
};

export function DocumentsTab({ dealId }: { dealId: string }) {
  const c = useThemeColors();
  const [docs, setDocs] = useState<DealDocument[]>([]);
  const [pdfs, setPdfs] = useState<CannabisPdf[]>([]);
  const [preview, setPreview] = useState<{ url: string; title: string } | null>(null);

  useEffect(() => {
    let active = true;
    (async () => {
      try {
        const res = await api.get<{ documents: DealDocument[] }>(`/submission/deal-documents/${dealId}`);
        if (active) setDocs(res.documents || []);
      } catch {
        if (active) setDocs([]);
      }
      try {
        const res = await api.get<{ pdfs: CannabisPdf[] }>(`/submission/applications/${dealId}`);
        if (active) setPdfs(res.pdfs || []);
      } catch {
        if (active) setPdfs([]);
      }
    })();
    return () => { active = false; };
  }, [dealId]);

  const card: React.CSSProperties = {
    background: c.cardBg,
    border: `1px solid ${c.borderColor}`,
    borderRadius: 12,
    overflow: "hidden",
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>
      {/* Applications — submission PDFs generated by the platform. */}
      <section>
        <h3 style={{ ...SECTION_LABEL, color: c.textMuted }}>Applications</h3>
        {pdfs.length === 0 ? (
          <p style={{ fontSize: 12.5, color: c.textMuted, margin: 0 }}>No application documents yet.</p>
        ) : (
          <div style={card}>
            {pdfs.map((p, i) => (
              <DocRow
                key={p.path}
                icon={<FileText style={{ width: 16, height: 16, color: c.textMuted, flexShrink: 0 }} />}
                name={p.label}
                meta="PDF"
                url={p.path}
                onPreview={() => setPreview({ url: p.path, title: p.label })}
                last={i === pdfs.length - 1}
                testId={`row-application-${p.documentType}`}
              />
            ))}
          </div>
        )}
      </section>

      {/* Generated documents — deal docs produced as the deal progresses. */}
      <section>
        <h3 style={{ ...SECTION_LABEL, color: c.textMuted }}>Generated Documents</h3>
        {docs.length === 0 ? (
          <p style={{ fontSize: 12.5, color: c.textMuted, margin: 0 }}>No generated documents yet.</p>
        ) : (
          <div style={card}>
            {docs.map((d, i) => {
              const url = d.metadata?.downloadPath || undefined;
              return (
                <DocRow
                  key={d.id}
                  icon={<File style={{ width: 16, height: 16, color: c.textMuted, flexShrink: 0 }} />}
                  name={d.name}
                  meta={d.status}
                  url={url}
                  onPreview={url ? () => setPreview({ url, title: d.name }) : undefined}
                  last={i === docs.length - 1}
                  testId={`row-generated-${d.id}`}
                />
              );
            })}
          </div>
        )}
      </section>

      {/* §6C carrier binder / policy — always available, even with no other docs. */}
      <PolicyDocumentsPanel dealId={dealId} onPreview={(url, title) => setPreview({ url, title })} />

      {preview && (
        <PdfPreviewModal url={preview.url} title={preview.title} onClose={() => setPreview(null)} />
      )}
    </div>
  );
}

/* -------------------------------------------------------------------- Tasks */
type TaskEntry = { id: string; taskName: string; assignedTo?: string | null; assigneeName?: string | null; dueDate?: string; status?: string };

export function TasksTab({ dealId }: { dealId: string }) {
  const c = useThemeColors();
  const [tasks, setTasks] = useState<TaskEntry[]>([]);
  const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({ taskName: "", assignedTo: "", dueDate: "" });
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    try {
      const rows = await api.get<TaskEntry[]>(`/deals/${dealId}/tasks`);
      setTasks(rows);
    } catch {
      setTasks([]);
    }
  }, [dealId]);

  useEffect(() => { load(); }, [load]);

  const create = async () => {
    if (!form.taskName.trim() || saving) return;
    setSaving(true);
    try {
      await api.post(`/tasks`, {
        dealId,
        taskName: form.taskName.trim(),
        assignedTo: form.assignedTo || null,
        dueDate: form.dueDate || null,
      });
      setForm({ taskName: "", assignedTo: "", dueDate: "" });
      setAdding(false);
      await load();
    } catch {
      /* surfaced by the empty list */
    } finally {
      setSaving(false);
    }
  };

  const input: React.CSSProperties = {
    background: c.inputBg, border: `1px solid ${c.inputBorder}`, borderRadius: 8,
    color: c.inputText, fontFamily: "inherit", fontSize: 13, padding: "8px 10px", width: "100%", boxSizing: "border-box",
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      <div style={{ display: "flex", justifyContent: "flex-end" }}>
        <GhostButton onClick={() => setAdding((v) => !v)} style={{ display: "flex", alignItems: "center", gap: 6, padding: "6px 12px", fontSize: 12 }}>
          <Plus style={{ width: 14, height: 14 }} />Add task
        </GhostButton>
      </div>

      {adding && (
        <div style={{ display: "flex", flexDirection: "column", gap: 8, background: c.cardBg, border: `1px solid ${c.borderColor}`, borderRadius: 10, padding: 12 }}>
          <input style={input} placeholder="Task name" value={form.taskName} onChange={(e) => setForm((f) => ({ ...f, taskName: e.target.value }))} />
          <input style={input} placeholder="Assigned to (optional)" value={form.assignedTo} onChange={(e) => setForm((f) => ({ ...f, assignedTo: e.target.value }))} />
          <input style={input} type="date" value={form.dueDate} onChange={(e) => setForm((f) => ({ ...f, dueDate: e.target.value }))} />
          <PinkButton onClick={create} style={{ padding: "8px 16px", fontSize: 12 }}>{saving ? "Saving\u2026" : "Create task"}</PinkButton>
        </div>
      )}

      {tasks.length === 0 && !adding && (
        <div style={{ padding: "32px 0", textAlign: "center", fontSize: 13, color: c.textMuted }}>No tasks yet.</div>
      )}
      {tasks.map((t) => (
        <div key={t.id} style={{ display: "flex", alignItems: "center", gap: 9, background: c.cardBg, border: `1px solid ${c.borderColor}`, borderRadius: 10, padding: "10px 12px" }}>
          <CheckSquare style={{ width: 16, height: 16, color: t.status === "completed" ? "#4caf50" : c.textMuted }} />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 13, color: c.textPrimary }}>{t.taskName}</div>
            {(t.assignedTo || t.dueDate) && (
              <div style={{ fontSize: 11, color: c.textMuted, display: "flex", alignItems: "center", gap: 4 }}>
                {t.assignedTo && t.assigneeName ? (
                  <UserMiniProfile userId={t.assignedTo}>
                    <button
                      type="button"
                      style={{ background: "none", border: "none", padding: 0, cursor: "pointer", fontSize: 11, color: "var(--accent-primary)", fontWeight: 600 }}
                    >
                      {t.assigneeName}
                    </button>
                  </UserMiniProfile>
                ) : t.assigneeName ? (
                  <span>{t.assigneeName}</span>
                ) : null}
                {(t.assigneeName) && t.dueDate ? <span>{"\u00b7"}</span> : null}
                {t.dueDate ? <span>{new Date(t.dueDate).toLocaleDateString()}</span> : null}
              </div>
            )}
          </div>
        </div>
      ))}
    </div>
  );
}

/* -------------------------------------------------------------------- Quote */
type QuoteRecord = {
  wcRatingBreakdown?: any;
  wfsRatingBreakdown?: any;
  workforceProfile?: any;
  ratedAt?: string;
  wcIndicationMin?: string | null;
  wcIndicationMax?: string | null;
  wcFinalPremium?: string | null;
  paramsPendingReview?: boolean | null;
};

export function QuoteTab({ dealId, businessName, productType, vertical, coverageEffectiveDate, detailMetric, onCloseDetail, canEditParams, onQuoteUpdated, onClose }: { dealId: string; businessName: string; productType?: string; vertical?: string; coverageEffectiveDate?: string | null; detailMetric?: IndicationMetric | null; onCloseDetail?: () => void; canEditParams?: boolean; onQuoteUpdated?: () => void; onClose: () => void }) {
  const c = useThemeColors();
  const [quote, setQuote] = useState<QuoteRecord | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [version, setVersion] = useState(0);

  useEffect(() => {
    let active = true;
    (async () => {
      try {
        const row = await api.get<QuoteRecord>(`/quotes/by-deal/${dealId}`);
        if (active) setQuote(row);
      } catch {
        if (active) setQuote(null);
      } finally {
        if (active) setLoaded(true);
      }
    })();
    return () => { active = false; };
  }, [dealId, version]);

  if (!loaded) return <div style={{ padding: "32px 0", textAlign: "center", fontSize: 13, color: c.textMuted }}>Loading quote\u2026</div>;

  // A header KPI was clicked — show the editable detail view for that metric
  // instead of the indication (works whenever the deal has a workforce profile).
  if (detailMetric && quote?.workforceProfile) {
    return (
      <IndicationDetailView
        dealId={dealId}
        metric={detailMetric}
        profile={quote.workforceProfile as WorkforceProfileShape}
        pendingReview={!!quote.paramsPendingReview}
        editable={!!canEditParams}
        onBack={() => onCloseDetail?.()}
        onSaved={() => {
          setVersion((v) => v + 1); // refresh premium/table with re-rated numbers
          onQuoteUpdated?.();
        }}
      />
    );
  }

  const wcBreakdown = quote?.wcRatingBreakdown?.data || quote?.wcRatingBreakdown;
  if (quote && wcBreakdown) {
    const isMulti = Array.isArray(wcBreakdown?.locations);
    if (isMulti) {
      return (
        <IndicationBreakdownPanel
          businessName={businessName}
          wcBreakdown={wcBreakdown}
          workforceProfile={quote.workforceProfile || null}
          indicationLow={quote.wcIndicationMin != null ? Number(quote.wcIndicationMin) : null}
          indicationHigh={quote.wcIndicationMax != null ? Number(quote.wcIndicationMax) : null}
          finalPremiumFallback={quote.wcFinalPremium != null ? Number(quote.wcFinalPremium) : null}
          ratedAt={quote.ratedAt}
          vertical={vertical}
          productType={productType}
          coverageEffectiveDate={coverageEffectiveDate}
        />
      );
    }
    return (
      <ProposalPanel
        businessName={businessName}
        quoteType={productType === "PEO" ? "PEO+WC" : "WC Only"}
        wcBreakdown={wcBreakdown}
        wfsBreakdown={quote.wfsRatingBreakdown?.data || quote.wfsRatingBreakdown}
        readOnly
        ratedAt={quote.ratedAt}
      />
    );
  }

  return (
    <div style={{ padding: "40px 20px", textAlign: "center" }}>
      <Calculator style={{ width: 40, height: 40, color: c.textMuted, marginBottom: 12 }} />
      <p style={{ fontSize: 15, color: c.textPrimary, margin: "0 0 8px" }}>No quote on file</p>
      <p style={{ fontSize: 13, color: c.textMuted, margin: "0 0 16px" }}>Generate a quote from the Marketplace.</p>
      <GhostButton onClick={onClose} style={{ padding: "8px 20px" }}>Close</GhostButton>
    </div>
  );
}

/* ------------------------------------------------------------------- Policy */
export function PolicyTab({ dealId, bindStatus }: { dealId: string; bindStatus?: string }) {
  const c = useThemeColors();
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: c.textMuted }}>
        <Shield style={{ width: 15, height: 15 }} />Bind & policy status
      </div>
      <BindStatusPanel dealId={dealId} bindStatus={bindStatus || "not_started"} />
    </div>
  );
}
